import type { CalorieAnalysis } from "@prisma/client";
import type {
  CalorieAiResponse,
  CalorieAnalysisResponse,
  CalorieAnalyzeInput,
  CalorieEstimate,
  CalorieItem,
} from "../types/calorieTypes";

export function buildCaloriePrompt(input: CalorieAnalyzeInput) {
  const context = [
    "Analyze this meal and estimate nutrition.",
    input.description ? `User description: ${input.description}` : null,
    input.imageName ? `Image file name: ${input.imageName}` : null,
    "Return JSON exactly like:",
    `{
  "mealName": "string",
  "calories": 520,
  "protein": 32,
  "carbs": 54,
  "fat": 18,
  "confidence": "low | medium | high",
  "notes": "short practical note",
  "items": [
    { "name": "rice", "calories": 220, "protein": 4, "carbs": 45, "fat": 1 }
  ]
}`,
    "If the image is unclear, say so in notes and make a conservative estimate.",
  ].filter(Boolean);

  return context.join("\n");
}

export function normalizeCalorieEstimate(
  parsed: CalorieAiResponse
): CalorieEstimate {
  return {
    mealName: parsed.mealName || "Estimated meal",
    calories: Math.max(0, Math.round(parsed.calories || 0)),
    protein: optionalNumber(parsed.protein),
    carbs: optionalNumber(parsed.carbs),
    fat: optionalNumber(parsed.fat),
    confidence: normalizeConfidence(parsed.confidence),
    notes: parsed.notes || "Estimate generated by AI. Use as guidance only.",
    items: normalizeItems(parsed.items),
  };
}

export function toCalorieAnalysisResponse(
  analysis: CalorieAnalysis,
  items: CalorieItem[]
): CalorieAnalysisResponse {
  return { ...analysis, items };
}

function optionalNumber(value: unknown) {
  return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}

function normalizeConfidence(value: string | undefined) {
  const normalized = value?.toLowerCase();
  if (normalized === "low" || normalized === "medium" || normalized === "high") {
    return normalized;
  }
  return "medium";
}

function normalizeItems(items: unknown) {
  if (!Array.isArray(items)) return [];
  return items
    .filter((item) => item?.name)
    .map((item) => ({
      name: String(item.name),
      calories: Number.isFinite(item.calories) ? Math.max(0, Math.round(item.calories)) : 0,
      protein: optionalNumber(item.protein),
      carbs: optionalNumber(item.carbs),
      fat: optionalNumber(item.fat),
    }));
}
